# Generated by Django 5.0.14 on 2026-04-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='latest_frame',
            field=models.ImageField(blank=True, null=True, upload_to='live/'),
        ),
        migrations.AddField(
            model_name='device',
            name='latest_frame_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
