# Generated by Django 5.0.14 on 2026-03-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='card_uid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
