"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!a9(5ic6lv4#i3rcuvsi$_dn15v=@j^oq&#dy$*(r-ne4vyq_&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'categories',
    'accounts',
    'violations',
    'vehicles',
    'api',
    'devices',
    'ai',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'categories.context_processors.menu_links',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

AUTH_USER_MODEL = 'accounts.Account'
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'violation_list'
LOGOUT_REDIRECT_URL = 'login'


# AI Settings
# AI_MODEL_PATH = BASE_DIR / "ai" / "models" / "best_hybrid_model.pth"
# AI_IMG_SIZE = 224
# AI_DEVICE = "cuda"   # hoặc "cpu"
# AI_CLASS_NAMES = [
#     "class_interior",
#     "class_personal",
#     "class_phone",
#     "class_safe",
# ]
# AI_CONF_THRESHOLD = 0.5   # Ngưỡng confidence để xác định vi phạm
# AI_VIOLATION_COOLDOWN_SECONDS = 10 # Thời gian chờ giữa các vi phạm của cùng 1 xe (theo license plate)
# AI_CLASS_TO_CATEGORY = {
#     "class_interior": "Phone",
#     "class_personal": "Personal",
#     "class_phone": "Phone",
#     "class_safe": "Safe",
# }


# DROWSINESS SETTINGS
DROWSINESS_MODEL_PATH = BASE_DIR / "ai" / "models" / "face_landmarker.task"
DROWSINESS_FPS = 4  # tốc độ frame ESP32 gửi

DROWSINESS_EYE_CLOSED_RATIO = 0.75 # nhạy theo baseline cá nhân, ví dụ baseline EAR = 0.3 thì ngưỡng nhắm mắt sẽ là 0.3 * 0.85 = 0.255
DROWSINESS_EYE_CLOSED_ABS = 0.20 # ngưỡng tuyệt đối fallback, nếu EAR < 0.20 thì cũng tính là nhắm mắt dù chưa calibrate được baseline
DROWSINESS_EYE_CLOSED_FRAMES = 2*DROWSINESS_FPS # nhắm khoảng 8 frame liên tục thì trigger, tương đương 8 / DROWSINESS_FPS giây, ví dụ 8 / 4 = 2 giây nhắm mắt liên tục sẽ bị tính là vi phạm


DROWSINESS_CATEGORY_NAME = "Drowsiness"
DROWSINESS_VIOLATION_COOLDOWN_SECONDS = 30 # thời gian chờ giữa các vi phạm của cùng 1 xe (theo license plate)

HEAD_TURN_CATEGORY_NAME = "Head Turn"
HEAD_TURN_VIOLATION_COOLDOWN_SECONDS = 20

DROWSINESS_HEAD_YAW_THRESHOLD = 25 # nếu head yaw > 25 độ thì cũng tính là vi phạm, tương đương quay đầu sang 1 bên quá nhiều
DROWSINESS_HEAD_TURN_VIOLATION_FRAMES = 2*DROWSINESS_FPS # nếu quay đầu quá nhiều trong 8 frame liên tục thì cũng tính là vi phạm
DROWSINESS_HEAD_TURN_DECAY = 1 # nếu head yaw > threshold thì tăng điểm quay đầu, nếu < threshold thì giảm điểm quay đầu theo decay, nếu điểm quay đầu > DROWSINESS_HEAD_TURN_VIOLATION_FRAMES thì tính là vi phạm


DROWSINESS_BUFFER_SECONDS = 5 # số giây dữ liệu buffer cho mỗi thiết bị
# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'
STATICFILES_DIRS = ['core/static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
