# Generated by Django 5.0.14 on 2026-01-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='severality_level',
            field=models.IntegerField(default=1),
        ),
    ]
