# Generated by Django 5.0.14 on 2026-01-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='violation',
            options={'ordering': ['-reported_at'], 'verbose_name': 'Violation', 'verbose_name_plural': 'Violations'},
        ),
    ]
