# Generated by Django 5.0.14 on 2026-01-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0002_alter_violation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
