# Generated by Django 5.0.14 on 2026-01-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0003_violation_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='title',
            field=models.CharField(default='Violation Report', max_length=200),
        ),
    ]
