# Generated by Django 5.2.13 on 2026-04-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0004_alter_violation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='violations/videos/'),
        ),
    ]
