# Generated by Django 5.2.13 on 2026-04-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('violations', '0006_violation_status_violationappeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violationappeal',
            name='reviewed_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
